
create table RFHOBBY (
	ID VARCHAR(5),
	NAMA VARCHAR(100),
	PRIMARY KEY (ID)
);

INSERT INTO RFHOBBY VALUES ('00001', 'Membaca');
INSERT INTO RFHOBBY VALUES ('00002', 'Sepabola');
INSERT INTO RFHOBBY VALUES ('00003', 'Basket');

create table MEMBER (
	ID VARCHAR(5),
	NAMA VARCHAR(100),
	EMAIL VARCHAR(50),
	PHONE VARCHAR(15),
	PRIMARY KEY (ID)
);

create table MEMBER_HOBBY (
	ID_MEMBER VARCHAR(5),
	ID_HOBBY VARCHAR(5)
);
